# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared 
  TRAIN_DATA: train.csv
  TEST_DATA: test.csv
  FEATUREZED_DATA: features
  FEATURIZED_DATA_TRAIN: train.pkl
  FEATURIZED_DATA_TEST: test.pkl
  MODEL_DIR: model
  MODEL_NAME: model.pkl
  

metrics:
   SCORES: scores.json
  

plots:
  PRC: prc.json
  ROC: roc.json
source_data: 
  data_dir: data
  data_file: data.xml 
  